### ISSUE TITLE
"this repository is empty"

### ISSUE THREAD

**Issue by neuromusic** [NeuroInfoPrimer/primer#1]
The text of http://dx.doi.org/10.1016/j.neuron.2016.05.039 indicates that this repo should contain the necessary code to generate the figures in the paper.
![image](https://cloud.githubusercontent.com/assets/1245615/17036637/f9a2cb2e-4f41-11e6-80df-d3bdae617200.png)

**Comment by neuromusic** [comment]
OK, I just added the scripts from the Supplemental zip file to a repo: http://github.com/neuromusic/SpikeTrainsPrimer but I can't open a pull request because this repo is empty

**Comment by benlansdell** [comment]
Thanks for pointing this out. The files have been added now

**Comment by neuromusic** [comment]
Fantastic!! Thanks!
